netbox_dns/tests/test_auto_ptr.py
fixes #85 
These tests cover most of the funtionality of the automatic PTR generation feature:
* Generate PTR records for A/AAAA records if a matching reverse zone is present
* Deleting PTR records when A/AAAA records are deleted
* Modifying PTR records when the A/AAAA record changes (whether the PTR is in the same reverse zone or not)
* Move or remove PTR records when a reverse zone is deleted, depending on whether there is a zone containing the prefixes of the address record's values or not
* Create or move PTR records to a newly created reverse zone, depening on whether they existed in any parent zone before or not
* Inhibit the creation of A/AAAA records with duplicate addresses unless all but one have "disable_ptr" set
* Change the TTL of the reverse record when the TTL of the …
=> Added unit tests for automatic generation of PTR records

.github/workflows/test.yml
Netbox 3.1 has breaking changes. For now run tests with v3.0.12.
Please see: #89
=> fix workflow until #89 fix.

netbox_dns/templates/netbox_dns/object_list.html, netbox_dns/templates/netbox_dns/record_list.html
Replace `validated_viewname` by `plugin_validated_viewname` in object list-like templates.
fixes #93
=> Fixed validated viewnames in templates

netbox_dns/api/serializers.py, netbox_dns/api/views.py, netbox_dns/forms.py, netbox_dns/models.py, netbox_dns/templates/netbox_dns/nameserver.html, netbox_dns/templates/netbox_dns/record.html, netbox_dns/templates/netbox_dns/zone.html, netbox_dns/tests/test_api.py, netbox_dns/views.py
fixes #89 (kind of)
Turns out there are a few more incompatible changes in 3.1.
The CustomField* classes are relatively uncritical as we actually don't use the functionality added by them, so I just replaced them with the corresponding non-CustomField methods. I'm not really sure that will put us on the safe side in the long run, but with 3.1 it is doing the trick.
Class BulkEditForm also implicitly inherits from BootstrapMixin implicitly, so we have the same issue here. Since we actually need its functionality (and it it pretty simple and short) I saw no better way in dealing with this than to copy it and include it in the forms.py module.
A different issue is, however, that the template tags_panel.html was renamed to `tags.html' in 3.1., breaking three of our templates, and we do …
=> Implemented Netbox 3.1 compatibility fixes

.github/workflows/test-nb-3.0.x.yml, netbox_dns/templates/netbox_dns/managed_record_list.html, netbox_dns/templates/netbox_dns/nameserver.html, netbox_dns/templates/netbox_dns/object_list.html, netbox_dns/templates/netbox_dns/record.html, netbox_dns/templates/netbox_dns/record_list.html, netbox_dns/templates/netbox_dns/zone.html, netbox_dns/templates/netbox_dns/zone_managed_record.html, netbox_dns/templates/netbox_dns/zone_record.html, netbox_dns/views.py
NetBox 3.1.2 has breaking changes. This PR should fix them.
table controls template location changed from `inc/table_controls.html` to `inc/table_controls_htmx.html`. fixes #112 
@peteeckel can you review my PR please.
=> fix NetBox 3.1.2 release breaking changes

netbox_dns/tables/record.py, netbox_dns/templates/netbox_dns/managed_record_list.html
fixes #132 
This PR contains fixes for the issues with managed record lists.
Essentially, all buttons except "Export" have been removed from the page, and `ManagedRecordTable` and `ZoneManagedRecordTable` have been modified so they only show supported actions in their `ActionColumn`.
This PR should be merged after #139.
=> Fix immutable object lists (managed records)

.github/workflows/black.yml
Recent changes in black have broke black workflow. See: psf/black#2964
This PR fixes the issue.
=> fix black workflow

netbox_dns/forms/record.py
Convert the record type to uppercase on Record bulk import.
fixes #167
=> Make the record type case insensitive in bulk import

netbox_dns/tables/record.py
This PR truncates the "value" field in record tables to 64 characters, which should be sufficient in most situations. The full value of any record field is still visible in the detail view.
fixes #169
=> Truncate the value field in record tables

netbox_dns/forms/record.py, netbox_dns/forms/view.py, netbox_dns/models.py, netbox_dns/tests/custom.py, netbox_dns/tests/record/test_validation.py, netbox_dns/tests/zone/test_api.py, pyproject.toml
This PR modifies the way records are validated before saving.
Up to now, only address records have been validated by checking if their value was a valid IPv4/IPv6 address. All other record types essentially were saved unchecked.
With this PR, validation of records was moved from forms to the model (which gives a a more thorough way of making sure only validated data go into the database and promptly broke one of the old tests that created an illegal SOA record), and all records that dnspython can validate are now validated to be compliant with the standards (at least as far as dnspython can check this). 
In addition, the list of available record types is now generated from the record types dnspython knows, which adds some additional record types to the supported types and makes sure new …
=> Validate records using dnspython

netbox_dns/models.py, netbox_dns/tests/record/test_validation.py
There are three checks that are performed:
- When a CNAME record is added to a zone that already has another record with the same name, the CNAME creation is denied.
- When a record with any type is added to a zone that already has a CNAME with the same name, the new record creation is denied.
- When a record with a singleton type is added to a zone that already has another record with the same type and name, the singleton record creation is refused.
This avoids creating zones that cannot be loaded by name servers.
fixes #180
fixes #72
=> Add validation for CNAME and singleton Record objects

netbox_dns/forms/record.py, netbox_dns/models.py, netbox_dns/tests/record/test_validation.py
This PR moves the remainder of the validation that was formerly in the record forms to the model.
In addition, the dirty hack used to make it possible to read zone/view names from CSV data was replaced by a proper solution that is closer to the Django standard and should also be quite a bit faster than the workaround. 
A test routine for case-insensitive RDtypes is included as well, as that was formerly only part of the forms and now it can be properly tested.
fixes #183
=> Redesigned record validation

netbox_dns/models.py, netbox_dns/tests/record/test_auto_ptr.py
This was kept undetected for a while ... though very easy to fix. Tests added.
fixes #188
=> Remove PTR record when record type changes from A/AAAA to something else

docs/using_netbox_dns.md, netbox_dns/models.py, netbox_dns/tests/record/test_auto_ptr.py, netbox_dns/tests/view/test_auto_ptr.py, netbox_dns/tests/view/test_zone.py
fixes #191 
This PR changes the behaviour of NetBox DNS to allow multiple PTR records for the same address. If, for example, address records are generated like this in zone `zone1.example.com`:
```
name1    86400    IN    A    10.0.1.1
name2    86400    IN    A    10.0.1.1
```
NetBox DNS will create two matching PTR records in zone `1.0.10.in-addr.arpa.`:
```
1    86400    IN    PTR    name1.zone1.example.com.
1    86400    IN    PTR    name2.zone1.example.com.
```
Before this change, NetBox DNS would not allow the second entry in order to keep the PTR record unique, which is, however, not a requirement and restricts the use of the tool in a way that actually makes it less generally usable.
Tests and documentation have been adjusted accordingly.
=> Allow multiple PTR records for the same address

netbox_dns/views/nameserver.py, netbox_dns/views/record.py, netbox_dns/views/view.py, netbox_dns/views/zone.py
After deleting an object, return to the object type's associated list view.
fixes #193
=> Return to the list view for an object type after deleting an object

netbox_dns/graphql/__init__.py, netbox_dns/graphql/nameserver.py, netbox_dns/graphql/record.py, netbox_dns/graphql/schema.py, netbox_dns/graphql/view.py, netbox_dns/graphql/zone.py
fixes #197 
The only issue that unfortunately cannot be fixed that easily is that the NetBox test framework could not be convinced to test GraphQL APIs for plugins. 
This is due to the fact that the test framework is quite inflexible and actually not supported for plugins at all - so we'll need to wait until support for the test framework (which, according to the NetBox maintainers, will probably require a general cleanup that is planned for a future release) until we can use it.
=> Initial implementation of GraphQL support

poetry.lock
This PR solves version solving issue about dnspython.
```
$ poetry install --no-interaction
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
SolverProblemError
Because netbox-dns depends on dnspython (^2.2.1) which doesn't match any versions, version solving failed.
at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
237│             packages = result.packages
238│         except OverrideNeeded as e:
239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
240│         except SolveFailure as e:
→ 241│             raise SolverProblemError(e)
242│ 
243│         results = dict(
244│ …
```
=> fix version solving issue

netbox_dns/models.py, netbox_dns/tests/view/test_zone.py, netbox_dns/tests/zone/test_auto_soa_serial.py
fixes #203 
This PR adds code that detects when a SERIAL has not been defined for a zone and SOA SERIAL autogeneration is turned off. Formerly, this was only detected when trying to add the SOA record to the zone and it didn't validate by dnspython checks, which led to a 500 error with an error message that does not make too much sense.
Now a proper error message like
```
{"soa_serial":["soa_serial is not defined and soa_serial_auto is disabled for zone zone5.example.com."]}
```
is returned with a 400 response code if a serial number cannot be determined.
=> Detect missing SOA serial number

netbox_dns/__init__.py, netbox_dns/tests/test_netbox_dns.py, pyproject.toml
=> release 0.11.1

netbox_dns/templates/netbox_dns/nameserver.html, netbox_dns/templates/netbox_dns/record.html, netbox_dns/templates/netbox_dns/view.html, netbox_dns/templates/netbox_dns/zone.html, netbox_dns/tests/zone/test_auto_soa_serial.py
Views were OK, but the detail views for all other object types were missing the custom fields.
fixes #208
=> Display custom fields for record, zones and name servers

netbox_dns/forms/record.py
Use `add_blank_choice` for the type choices in the bulk edit form. This results in an initially empty field instead of a default value of `A`.
fixes #210
=> Set the default type to unset when bulk editing records

netbox_dns/forms/zone.py, netbox_dns/tests/zone/test_api.py
fixes #214
This PR also fixes the behaviour of the CSV import when a `soa_mname` has not been given, in which case a default value in the config file is required. Unfortunately this didn't work, the import kept complaining that a string isn't a valid choice for `soa_mname`.
=> Fixed zone CSV import

netbox_dns/models.py, netbox_dns/tests/zone/test_auto_soa.py
fixes #217
This PR is a complete redesign of how SOA records are generated and parsed. NetBox DNS now uses dnspython both for generating SOA records and for parsing them in the test suite.
After applying this upgrade, any change to a zone that creates a new SOA record will use the correct format without parentheses. To manually update all SOA records, run `netbox/manage.py update_soa [--verbose]` from the shell.
=> Create and parse SOA records using dnspython

netbox_dns/models.py
On saving a new record, avoid calling Djano's `save()` method twice.
Though normally not a problem at all, this breaks record creation using the API for some reason. There should also be a small performance improvement, and avoiding the double save is cleaner as well.
fixes #232
=> Avoid duplicate save() operation for new records

.github/workflows/publish.yml, .github/workflows/release.yml
Older version of poetry installer is deprecated. This causes to github actions fail. This PR should fix the issue.
=> Fix poetry version for release 0.14.0

netbox_dns/migrations/0018_update_ns_ttl.py, netbox_dns/migrations/0019_update_ns_ttl.py, netbox_dns/models.py
fixes #242 
This very small change sets a zone's default TTL to None for all new and updated zones, as well as for all existing zones via a data migration.
As a result, NS records will still follow the zone's default TTL if the zone data are created with a `$TTL` tag or similar mechanism in place (which is recommended anyway to avoid falling back to the SOA `MINIMUM_TTL` setting for successful queries).
@hatsat32: This PR can't be merged together with #240 as both have migrations. That needs to be fixed when the merge conflict pops up.
=> Set TTL for the zones' NS records to None

netbox_dns/models.py, netbox_dns/tests/record/test_auto_ptr.py
fixes #246
The FQDN for a record with @ as its name must be the name of the zone, not `@.` with the zone name appended.
=> Fix FQDN generation for @ records

netbox_dns/templates/netbox_dns/zone_managed_record.html, netbox_dns/templates/netbox_dns/zone_record.html
fixes #249 
The issue was a result of using render_table with the django-tables2 default template. Using the NetBox table.html template and moving the paginator a bit to match the standard NetBox page style should clean that up.
=> Improved pagination for zone record/managed record tables

netbox_dns/migrations/0022_search.py, netbox_dns/models.py, netbox_dns/tests/zone/test_auto_ns.py
fixes #279
This fixes the above issue by updating NS and SOA records for affected zones when a NameServer object is deleted or renamed.
Additionally, some new tests covering both cases were added, and the `update_ns_records()` got some performance improvement as well.
=> Modify NS and SOA records for affected zones when a NameServer object is deleted or renamed
