netbox_dns/models.py

Added more dns record types
* SOA
* SRV
* PTR
* SPF
* CAA
* DS
* SSHFP
* TLSA
This should be enought for general use.
closes: #7

add more dns record types

---

netbox_dns/forms.py

* filter forms more attributes added
* improved ui

better forms implemented

---

netbox_dns/forms.py
netbox_dns/tables.py
netbox_dns/templates/netbox_dns/object_list.html
netbox_dns/tests/test_views.py
netbox_dns/urls.py
netbox_dns/views.py

Bulk edit and bulk delete features implemented

Add bulk edit and delete actions

---

.github/workflows/test.yml
netbox_dns/__init__.py
netbox_dns/filters.py
netbox_dns/forms.py
netbox_dns/models.py
netbox_dns/tables.py
netbox_dns/templates/netbox_dns/record.html
netbox_dns/templates/netbox_dns/zone.html
netbox_dns/tests.py
netbox_dns/tests/test_netbox_dns.py
netbox_dns/views.py
pyproject.toml

- improve ui
- fix record filtering
- code formating
- remove unnecessary comments

various improvements

---

netbox_dns/views.py

add export feature

---

netbox_dns/api/serializers.py
netbox_dns/api/views.py
netbox_dns/templates/netbox_dns/nameserver.html
netbox_dns/views.py

fixes #19
(well, at least the part that is fixable without touching the Netbox code)

Implemented zone list in the NameServer view

---

netbox_dns/tables.py

Add default_columns to RecordTable.

refactor record table

---

netbox_dns/__init__.py
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

Prepare for release 0.6.0 :tada:

prepare for release 0.6.0

---

netbox_dns/migrations/0004_create_ptr_for_a_aaaa_records.py

Run the data migration for A/AAAA PTR records non-atomically

---

netbox_dns/filters.py
netbox_dns/forms.py

Provide zone field in the record filter set

---

netbox_dns/models.py

Do not try to update pointers for non-existing address records

---

netbox_dns/forms.py

Make SOA MNAME bulk-editable

---

netbox_dns/forms.py

Allow disable_ptr on record CSV import

---

netbox_dns/tests/test_auto_soa.py

Added a test suite for the Auto SOA record feature

---

netbox_dns/templates/netbox_dns/zone_record.html

Fixed display error in zone record view

---

netbox_dns/forms.py
netbox_dns/urls.py
netbox_dns/views.py

Added BulkEdit functionality for Name Servers

---

netbox_dns/filters.py
netbox_dns/forms.py

- Removed the "Search" field from NameServer filters, as it only duplicates the functionality of the "Name" field.
- Added value and zone filtering to the Record filter.
- Set the "Search" placeholder text to a short summary what fields will be used for filtering.
fixes #97

Improved the filter interface

---

netbox_dns/models.py

fixes #100
The performance problem described in #100 is a result of always trying to update **all** A/AAAA record's PTR record when any new reverse zone turns up, either by renaming an old one or by adding it as a new zone.
The logic can be improved significantly by selecting which records are to be considered for updating:
- Records that do not have a PTR record at all and do not have PTR generation disabled.
- Records that do have a PTR record in a parent zone (identical suffix, but less labels) of the new or renamed zone.
All other records can be safely left alone.

Improved performance of renaming or adding reverse zones

---

netbox_dns/__init__.py
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

This release comes with a lot of new features and NetBox 3.1 support.

prepare for release 0.7.0

---

netbox_dns/forms.py

Add default option for SOA MNAME and nameservers when creating new zones

---

netbox_dns/migrations/0005_update_ns_records.py
netbox_dns/migrations/0006_zone_soa_serial_auto.py

Execute migration 0005 after 0007

---

netbox_dns/api/serializers.py

Added create() and update() methods for the Zone serializer

---

netbox_dns/forms.py

Fixed initial values of "nameservers" and "soa_mname" when editing zones

---

netbox_dns/__init__.py
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

After the release of netbox 3.1.2 with breaking changes and fixing some bugs,  I think we can release a new version: 0.8.0

prepare for release 0.8.0

---

netbox_dns/forms.py

Detect when multiple A/AAAA records with identical values try to enable PTR

---

netbox_dns/migrations/0010_update_soa_records.py
netbox_dns/models.py
netbox_dns/tests/zone/test_auto_soa.py

fixes #143 
This PR should be applied after #139.

Fix: Make sure that SOA MNAME/RNAME fields have a trailing dot

---

netbox_dns/filters/nameserver.py

fixes #134
This is essentially the fix from #135 applied to the refactored code tree.
This PR should be merged after #139.

Fix Quick Search for NameServer objects

---

netbox_dns/forms/record.py

fixes #140 (again).
This is essentially PR #141 applied to the refactored code tree.
This PR should be merged after #139.

Fix PTR record conflict with Bulk Edit

---

netbox_dns/models.py

fixes #151
This PR should be merged after #139.

Fix "@" record text representation

---

.github/workflows/black.yml
netbox_dns/__init__.py
netbox_dns/templates/netbox_dns/zone_managed_record.html
netbox_dns/templates/netbox_dns/zone_record.html
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

Load missing view_helpers

---

netbox_dns/__init__.py
netbox_dns/templates/netbox_dns/managed_record_list.html
netbox_dns/templates/netbox_dns/object_list.html
netbox_dns/templates/netbox_dns/record_list.html
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

Fixes quick search in these pages.
* Zone list
* Record list
* Nameserver list
* Managed record list
Unfortunately I could not found any proper solution in these pages.
* zone detail / records
* zone detail / managed records.
fixes #142

fix quick search

---

.github/workflows/test.yml
netbox_dns/__init__.py
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

This is the fist release for new netbox plugin api.
I changed test workflow action branch/ref to default (master)

prepere for release 0.10.0

---

netbox_dns/models.py

Remove metatypes/classes from the list of valid RDtypes/classes

---

netbox_dns/api/views.py
netbox_dns/views/nameserver.py
netbox_dns/views/record.py
netbox_dns/views/view.py
netbox_dns/views/zone.py

Prefetch objects on some performance-critical views

---

netbox_dns/forms/record.py

Make record type and value bulk editable

---

netbox_dns/models.py

Make it possible to clone View objects

---

netbox_dns/__init__.py
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

Prepare for release 0.11.0

---

netbox_dns/__init__.py
netbox_dns/tests/test_netbox_dns.py
pyproject.toml

Prepare for release 0.13.0

---

netbox_dns/api/nested_serializers.py

This PR restores compatibility with NetBox 3.3.0
fixes #220

Fixed import path for WritableNestedSerializer

---

netbox_dns/api/serializers.py

Expose custom fields via the API

---

netbox_dns/filters/zone.py

Make it possible to filter for the "active" annotation in zones

---

netbox_dns/navigation.py

Define permissions required to see navigation menu items

---

netbox_dns/api/serializers.py

Fixes #230 
Nested serializer in read only mode

Add zones nested serializer to nameservers

---

netbox_dns/models.py

fixes #239
This change skips most of the save() function for zones when only the SOA serial has to be updated. Some code related to the migration from very early versions of NetBox DNS to a consistent database (essentially getting rid of duplicate SOA entries, which should no longer exist in a recent installation) was removed.

Improved the performance of automatic SOA serial generation

---

examples/ansible/code/zone.db.j2
examples/ansible/using_netbox_dns_with_ansible.md

fixes #244
Inserted code to cater for null TTL values in records

Fix the ansible example for null TTL values in records

---

netbox_dns/fields/network.py

Form field needs to inherit from django.forms

---

netbox_dns/migrations/0018_zone_arpa_network.py

fixes #271
Subject says it all ...

Fixed typo in migration 0018

---

README.md

Fixed minimum NetBox version

---

netbox_dns/migrations/0022_search.py

Rebuild global search indexes after upgrade
